/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-interface=CloudflareEnv cloudflare-env.d.ts --include-runtime=false`
// 运行时全局类型（D1Database / Fetcher / KVNamespace 等）由 @cloudflare/workers-types 提供
//（见 tsconfig.json compilerOptions.types），不随本文件生成，便于依赖升级与安全扫描。
interface __BaseEnv_CloudflareEnv {
	DB: D1Database;
	ASSETS: Fetcher;
	OPENAI_API_KEY: string;
	OPENAI_BASE_URL: string;
	OPENAI_MODEL: string;
	SESSION_SECRET: string;
	ZHIHU_ACCESS_SECRET: string;
	ZHIHU_OAUTH_APP_ID: string;
	ZHIHU_OAUTH_APP_KEY: string;
	NEXT_PUBLIC_APP_TITLE: string;
	NEXT_PUBLIC_APP_DESCRIPTION: string;
	NEXT_PUBLIC_SITE_URL: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "OPENAI_API_KEY" | "OPENAI_BASE_URL" | "OPENAI_MODEL" | "SESSION_SECRET" | "ZHIHU_ACCESS_SECRET" | "ZHIHU_OAUTH_APP_ID" | "ZHIHU_OAUTH_APP_KEY" | "NEXT_PUBLIC_APP_TITLE" | "NEXT_PUBLIC_APP_DESCRIPTION" | "NEXT_PUBLIC_SITE_URL">> {}
}
