/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: dac3366ad5030e43a4091a6ff5e1f03d)
interface __BaseEnv_CloudflareEnv {
	WORK_UPLOADS: R2Bucket;
	DB: D1Database;
	STORY_GENERATION_QUEUE: Queue;
	ASSETS: Fetcher;
	OPENAI_API_KEY: string;
	OPENAI_BASE_URL: string;
	OPENAI_MODEL: string;
	SESSION_SECRET: string;
	ZHIHU_ACCESS_SECRET: string;
	ZHIHU_OAUTH_APP_ID: string;
	ZHIHU_OAUTH_APP_KEY: string;
	NEXT_PUBLIC_APP_TITLE: string;
	NEXT_PUBLIC_APP_DESCRIPTION: string;
	NEXT_PUBLIC_SITE_URL: string;
	NEXT_PUBLIC_GUEST_EXPERIENCE: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "OPENAI_API_KEY" | "OPENAI_BASE_URL" | "OPENAI_MODEL" | "SESSION_SECRET" | "ZHIHU_ACCESS_SECRET" | "ZHIHU_OAUTH_APP_ID" | "ZHIHU_OAUTH_APP_KEY" | "NEXT_PUBLIC_APP_TITLE" | "NEXT_PUBLIC_APP_DESCRIPTION" | "NEXT_PUBLIC_SITE_URL" | "NEXT_PUBLIC_GUEST_EXPERIENCE">> {}
}
